// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDynjbpDgEpinBm9BetCXUtMsrZfPNwueo',
    appId: '1:1065773319377:android:e1b9285365db53ceb8f1f0',
    messagingSenderId: '1065773319377',
    projectId: 'botapp-2a1e3',
    storageBucket: 'botapp-2a1e3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4hwA4QkZ4_481-6gCGC9G1xHe3lv3cIo',
    appId: '1:881686216361:ios:50ab80d239970e2d0773b8',
    messagingSenderId: '881686216361',
    projectId: 'solar-a1dbb',
    storageBucket: 'solar-a1dbb.appspot.com',
    androidClientId:
        '881686216361-jif29pnaripbmeskse6o9iatuppn4vgg.apps.googleusercontent.com',
    iosClientId:
        '881686216361-u0u6g81b53e3d7aih41j2mcle970p38i.apps.googleusercontent.com',
    iosBundleId: 'com.botManagement.bot',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCSUbdnpUaW2W31S1IVfdfnem4j1A7_FI',
    appId: '1:1065773319377:web:e7bea717d4cba04db8f1f0',
    messagingSenderId: '1065773319377',
    projectId: 'botapp-2a1e3',
    authDomain: 'botapp-2a1e3.firebaseapp.com',
    storageBucket: 'botapp-2a1e3.firebasestorage.app',
  );
}
